[package]
name = "quickwit-doc-mapper"
version = "0.6.5-dev"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Quickwit index configuration"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
dyn-clone = { workspace = true }
fnv = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
mockall = { workspace = true, optional = true }
nom = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
siphasher = { workspace = true }
tantivy = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
typetag = { workspace = true }
utoipa = { workspace = true }

quickwit-datetime = { workspace = true }
quickwit-macros = { workspace = true }
quickwit-common = { workspace = true }
quickwit-query = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
matches = { workspace = true }
proptest = { workspace = true }
serde_yaml = { workspace = true }
time = { workspace = true }

quickwit-proto = { workspace = true }
quickwit-query = { workspace = true, features = ["testsuite"] }

[features]
multilang = ["quickwit-query/multilang"]
testsuite = ["multilang"]

[[bench]]
name = "doc_to_json_bench"
harness = false
