[package]
name = "quickwit-storage"
version = "0.6.5-dev"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Quickwit's storage abstraction"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
bytesize = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
hyper = { workspace = true }
lru = { workspace = true }
md5 = { workspace = true }
mockall = { workspace = true, optional = true }
once_cell = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tantivy = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }

aws-config = { workspace = true }
aws-credential-types = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-smithy-http = { workspace = true }
aws-smithy-types = { workspace = true }

azure_core = { workspace = true, optional = true }
azure_storage = { workspace = true, optional = true }
azure_storage_blobs = { workspace = true, optional = true }

quickwit-aws = { workspace = true }
quickwit-common = { workspace = true }
quickwit-config = { workspace = true }
quickwit-proto = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
proptest = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }

aws-sdk-s3 = { workspace = true, features = ["test-util"] }
aws-smithy-client = { workspace = true, features = ["test-util"] }

quickwit-common = { workspace = true, features = ["testsuite"] }

[features]
azure = [
  "azure_core",
  "azure_storage",
  "azure_storage_blobs",
  "azure_core/enable_reqwest_rustls",
  "azure_storage/enable_reqwest_rustls",
  "azure_storage_blobs/enable_reqwest_rustls",
]
ci-test = []
testsuite = [
  "azure",
  "azure_core/azurite_workaround",
  "azure_storage_blobs/azurite_workaround",
  "mockall",
]
