[package]
name = "quickwit-proto"
version = "0.6.5-dev"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Quickwit's protos"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
dyn-clone = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
futures = { workspace = true, optional = true }
mockall = { workspace = true, optional = true }
opentelemetry = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
ulid = { workspace = true }
utoipa = { workspace = true }

quickwit-actors = { workspace = true }
quickwit-common = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
futures = { workspace = true }

[build-dependencies]
glob = "0.3.1"
prost-build = { workspace = true }
tonic-build = { workspace = true }

quickwit-codegen = { workspace = true }

[features]
postgres = [ "sqlx" ]
testsuite = [ "mockall", "futures" ]
