[package]
name = "quickwit-config"
version = "0.6.5-dev"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial license, contact hello@quickwit.io
description = "Quickwit configuration"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
bytesize = { workspace = true }
chrono = { workspace = true }
cron = { workspace = true }
enum-iterator = { workspace = true }
humantime = { workspace = true }
itertools = { workspace = true }
json_comments = { workspace = true }
new_string_template = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
vrl = { workspace = true, optional = true }

quickwit-common = { workspace = true }
quickwit-doc-mapper = { workspace = true }
quickwit-macros = { workspace = true }
quickwit-proto = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[features]
testsuite = []
vrl = ["dep:vrl"]
