[package]
name = "quickwit-query"
version = "0.6.5-dev"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Quickwit's query DSL"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
fnv = { workspace = true }
hex = { workspace = true }
lindera-core = { workspace = true, optional = true}
lindera-dictionary = { workspace = true, optional = true }
lindera-tokenizer = { workspace = true, optional = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tantivy = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
whichlang = { workspace = true, optional = true }

quickwit-common = { workspace = true }
quickwit-datetime = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }
time = { workspace = true }

[features]
multilang = [
    "lindera-core",
    "lindera-dictionary",
    "lindera-tokenizer",
    "whichlang",
]

testsuite = [
    "multilang",
]

[[bench]]
name = "tokenizers_bench"
harness = false

[[bench]]
name = "multilang_tokenizers_bench"
harness = false
