[package]
name = "quickwit-indexing"
version = "0.6.5-dev"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Quickwit indexing"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
aws-config = { workspace = true, optional = true }
aws-smithy-client = { workspace = true, optional = true }
aws-sdk-kinesis = { workspace = true, optional = true }

anyhow = { workspace = true }
arc-swap = { workspace = true }
async-trait = { workspace = true }
backoff = { workspace = true, optional = true }
bytes = { workspace = true }
bytesize = { workspace = true }
chitchat = { workspace = true }
fail = { workspace = true }
flume = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
google-cloud-auth = { workspace = true, optional = true }
google-cloud-default = { workspace = true, optional = true }
google-cloud-gax = { workspace = true, optional = true }
google-cloud-googleapis = { workspace = true, optional = true }
google-cloud-pubsub = { workspace = true, optional = true }
itertools = { workspace = true }
libz-sys = { workspace = true, optional = true }
once_cell = { workspace = true }
oneshot = { workspace = true }
openssl = { workspace = true, optional = true }
pulsar = { workspace = true, optional = true }
quickwit-query = { workspace = true }
rdkafka = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
tantivy = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }
utoipa = { workspace = true }
vrl = { workspace = true, optional = true }

quickwit-actors = { workspace = true }
quickwit-aws = { workspace = true }
quickwit-cluster = { workspace = true }
quickwit-common = { workspace = true }
quickwit-config = { workspace = true }
quickwit-directories = { workspace = true }
quickwit-doc-mapper = { workspace = true }
quickwit-ingest = { workspace = true }
quickwit-metastore = { workspace = true }
quickwit-opentelemetry = { workspace = true }
quickwit-proto = { workspace = true }
quickwit-storage = { workspace = true }

[features]
gcp-pubsub = ["dep:google-cloud-pubsub", "dep:google-cloud-default", "dep:google-cloud-googleapis", "dep:google-cloud-auth", "dep:google-cloud-gax"]
gcp-pubsub-emulator-tests = []
kafka = ["rdkafka", "backoff"]
kafka-broker-tests = []
kinesis = ["aws-config", "aws-smithy-client", "aws-sdk-kinesis", "quickwit-aws/kinesis"]
kinesis-localstack-tests = []
pulsar = ["dep:pulsar"]
pulsar-broker-tests = []
vendored-kafka = ["kafka", "libz-sys/static", "openssl/vendored", "rdkafka/gssapi-vendored"]
vendored-kafka-macos = ["kafka", "libz-sys/static", "openssl/vendored"]
testsuite = [
  "quickwit-actors/testsuite",
  "quickwit-cluster/testsuite",
  "quickwit-common/testsuite",
]
vrl = ["dep:vrl", "quickwit-config/vrl"]

[dev-dependencies]
bytes = { workspace = true }
criterion = { workspace = true, features = ["async_tokio"] }
mockall = { workspace = true }
proptest = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
tempfile = { workspace = true }

quickwit-actors = { workspace = true, features = ["testsuite"] }
quickwit-cluster = { workspace = true, features = ["testsuite"] }
quickwit-common = { workspace = true, features = ["testsuite"] }
quickwit-config = { workspace = true, features = ["testsuite"] }
quickwit-doc-mapper = { workspace = true, features = ["testsuite"] }
quickwit-ingest = { workspace = true, features = ["testsuite"] }
quickwit-metastore = { workspace = true, features = ["testsuite"] }
quickwit-proto = { workspace = true, features = ["testsuite"] }
quickwit-storage = { workspace = true, features = ["testsuite"] }

[[test]]
name = "failpoints"
path = "failpoints/mod.rs"
required-features = ["fail/failpoints"]

[[bench]]
name = "doc_process_vrl_bench"
harness = false
